// swift-tools-version: 5.9
// Generated by pre-release.sh — do not edit manually.
// Version: 2.0.0  Checksum (zip): 918dbdce239aac3430b9fe5e299961ff61eff525421cce893091701ffbd114fd
import PackageDescription

let package = Package(
    name: "lifestream-XCFramework",
    platforms: [
        .iOS(.v13)
    ],
    products: [
        .library(
            name: "LifestreamSDK",
            targets: ["LifestreamSDK"]
        ),
    ],
    targets: [
        .binaryTarget(
            name: "LifestreamSDK",
            path: "LifestreamSDK.xcframework"
        )
    ]
)
